# Generated by Django 2.2.11 on 2020-03-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=200)),
                ('temporadas', models.CharField(max_length=200)),
                ('finalizado', models.BooleanField()),
                ('visto', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
