# Generated by Django 2.2.11 on 2020-03-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='visto',
            field=models.CharField(max_length=4),
        ),
    ]
